services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - instant-messaging-app-postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80" # Map frontend to port 3000
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: ["./instant-messaging-app", "api"]
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: instant_messaging_app
      DB_PORT: 5432
      JWT_SECRET: deluge-tycoon-unstable
      APP_PORT: 8080
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    restart: unless-stopped

  user-service-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-1
    command: ["./instant-messaging-app", "user"]
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: instant_messaging_app
      DB_PORT: 5432
      JWT_SECRET: deluge-tycoon-unstable
      APP_PORT: 8080
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

  message-service-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-service-1
    command: ["./instant-messaging-app", "message"]
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: instant_messaging_app
      DB_PORT: 5432
      JWT_SECRET: deluge-tycoon-unstable
      APP_PORT: 8080
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

volumes:
  instant-messaging-app-postgres:
